const ActionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
};

export default ActionTypes;